# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches:
      - 'Production'

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: install node dependencies
      working-directory: ./Backend/LogisticsAPI
      run: | 
        npm install
        npm install -g nodemon
        npm install --save reflect-metadata rxjs
    - name: install angular dependencies
      working-directory: ./Frontend/lab5frontend
      run: | 
        npm install
        npm config set legacy-peer-deps true
        npm install -g @angular/cli@latest
    - name: Pm2 job runner
      run: | 
        pm2 start ecosystemAll.config.js
        pm2 ps
